<%@ Page Title="" Language="C#" MasterPageFile="~/Home.Master" AutoEventWireup="true" CodeBehind="RestaurantDetails.aspx.cs" Inherits="Foodie.DisplayDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder" runat="server">
    <asp:GridView ID="RestaurantDetails" runat="server" AutoGenerateColumns="false" DataKeyNames="RestaurantId" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" OnRowCancelingEdit="RestaurantDetails_RowCancelingEdit" OnRowDeleting="RestaurantDetails_RowDeleting" OnRowEditing="RestaurantDetails_RowEditing" OnRowUpdating="RestaurantDetails_RowUpdating" OnSelectedIndexChanged="RestaurantDetails_SelectedIndexChanged1">
        <Columns>
            <asp:TemplateField HeaderText="RestaurantName" runat="server">
                <EditItemTemplate><asp:TextBox ID="txtRestaurantName" runat="server" Text='<%# Bind("RestaurantName") %>'></asp:TextBox> </EditItemTemplate>
                <ItemTemplate><asp:Label ID="lblRestaurantName" runat="server" Text='<%# Bind("RestaurantName") %>' ></asp:Label></ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="RestaurantType" runat="server">
                <EditItemTemplate><asp:TextBox ID="txtRestaurantType" runat="server" Text='<%# Bind("RestaurantType") %>'></asp:TextBox> </EditItemTemplate>
                <ItemTemplate><asp:Label ID="lblRestaurantType" runat="server" Text='<%# Bind("RestaurantType") %>'></asp:Label></ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Location" runat="server">
                <EditItemTemplate><asp:TextBox ID="txtLocation" runat="server" Text='<%# Bind("Location") %>'></asp:TextBox> </EditItemTemplate>
                <ItemTemplate><asp:Label ID="lblLocation" runat="server" Text='<%# Bind("Location") %>' ></asp:Label></ItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>

